---
  :release: vivid
  :size: 4G
  :parted: parted.txt
  :rootfs:
    :url: https://releases.linaro.org/15.06/ubuntu/vivid-images/nano/linaro-vivid-nano-20150618-705.tar.gz
    :md5sum: c23a923bd8983a3ae8ce710d601983c2
  :firmware:
    :url: https://github.com/netrunner-arm/c1_prebuilt/archive/master.tar.gz
    :md5sum: 74f3a83b7024dc11bec9f8854183d90f
  :login:
    :username: ubuntu
    :password: ubuntu
    :groups:
      - sudo
