---
  :release: vivid
  :size: 4G
  :parted: parted.txt
  :rootfs:
    :url: https://releases.linaro.org/15.06/ubuntu/vivid-images/nano/linaro-vivid-nano-20150618-705.tar.gz
    :md5sum: df15a61bb11e634b5c7e78379a67e8d9
  :firmware:
    :backend: apt
    :sources:
      :cubox_repo: http://obs.jm0.eu:82/BSP:/IMX6/Ubuntu_Trusty/ ./
    :packages:
      - kernel-3.14.y-fslc-imx6-sr
      - u-boot-cubox-i
      - irqbalance-imx
  :bootloader:
    :config:
      :src: uEnv.txt.rb
      :dst: boot/uEnv.txt
    :uboot:
      :SPL:
        :file: boot/cubox-i-spl.bin
        :dd_opts: "bs=1K seek=1"
      :img:
        :file: boot/u-boot.img
        :dd_opts: "bs=1K seek=42"
  :login:
    :username: ubuntu
    :password: ubuntu
    :groups:
      - sudo
