---
  :release: netrunner-full
  :size: 6G
  :parted: parted.txt
  :rootfs:
    :url: http://pangea-data.s3-ap-southeast-2.amazonaws.com/dci/images/stable/armhf/netrunner-debian/latest/netrunner-debian-full_20160429.1445-armhf.tar.tar
  :firmware:
    :backend: apt
    :keys:
      - 5360FB9DAB19BAC9
    :sources:
      :c1: http://deb.odroid.in/c1/ trusty main
      :odroid: http://deb.odroid.in/ trusty main
      :dci_odroid: http://dci.ds9.pub:8080/odroid stable main
    :packages:
      # Kernel and some basic utilities
      - linux-image-c1
      - u-boot
      - u-boot-tools
      - bootini

      # Special X11 packages for the ODROID
      - mali-x11/stable
      - xserver-xorg-video-mali/stable

      # Set resolution on boot script
      - odroid-boot-services
      - calamares-core

  :bootloader:
    :config:
      :src: boot.ini.erb
      :dst: boot/boot.ini
    :uboot:
      :bl1:
        :file: usr/share/c1_uboot/bl1.bin.hardkernel
        :dd_opts: "bs=1 count=442"
      :SPL:
        :file: usr/share/c1_uboot/bl1.bin.hardkernel
        :dd_opts: "bs=512 skip=1 seek=1"
      :img:
        :file: usr/share/c1_uboot/u-boot.bin
        :dd_opts: "bs=512 seek=64"
