---
  :release: vivid
  :size: 4G
  :parted: parted.txt
  :rootfs:
    :url: https://releases.linaro.org/15.06/ubuntu/vivid-images/nano/linaro-vivid-nano-20150618-705.tar.gz
    :md5sum: df15a61bb11e634b5c7e78379a67e8d9
  :firmware:
    :backend: apt
    :sources:
      :c1: http://deb.odroid.in/c1/ trusty main
      :odroid: http://deb.odroid.in/ trusty main
    :packages:
      - linux-image-c1
      - u-boot
      - u-boot-tools
      - bootini
  :bootloader:
    :config:
      :src: boot.ini.erb
      :dst: boot/boot.ini
    :uboot:
      :bl1:
        :file: usr/share/c1_uboot/bl1.bin.hardkernel
        :dd_opts: "bs=1 count=442"
      :SPL:
        :file: usr/share/c1_uboot/bl1.bin.hardkernel
        :dd_opts: "bs=512 skip=1 seek=1"
      :img:
        :file: usr/share/c1_uboot/u-boot.bin
        :dd_opts: "bs=512 seek=64"
  :login:
    :username: ubuntu
    :password: ubuntu
    :groups:
      - sudo
