---
  :release: vivid
  :size: 4G
  :parted: parted.txt
  :rootfs:
    :url: https://releases.linaro.org/15.06/ubuntu/vivid-images/nano/linaro-vivid-nano-20150618-705.tar.gz
    :md5sum: df15a61bb11e634b5c7e78379a67e8d9
  :firmware:
    :backend: apt
    :url: https://github.com/raspberrypi/firmware/archive/master.tar.gz
    :md5sum: 2800f7493f2ed4a7fea12baa919641a3
  :login:
    :username: ubuntu
    :password: ubuntu
    :groups:
      - sudo
