---
  :release: vivid
  :size: 8G
  :parted: parted.txt
  :rootfs:
    :url: http://pangea-data.s3.amazonaws.com/dci/images/armhf/plasma5/latest/live-image-armhf.tar.tar.gz
  :firmware:
    :backend: tar
    :url: https://github.com/shadeslayer/rpi2_firmware/archive/master.tar.gz
  :bootloader:
    :config:
      :src: cmdline.txt.erb
      :dst: cmdline.txt
