---
  :release: netrunner
  :size: 5G
  :parted: parted.txt
  :rootfs:
    :url: http://pangea-data.s3.amazonaws.com/dci/images/armhf/live-image-armhf.tar.tar.gz
  :firmware:
    :backend: apt
    :keys:
      - 5360FB9DAB19BAC9
    :sources:
      :c1: http://deb.odroid.in/c1/ trusty main
      :odroid: http://deb.odroid.in/ trusty main
      :dci_odroid: http://pangea-data.s3.amazonaws.com/dci/odroid/debian sid main
    :packages:
      # Kernel and some basic utilities
      - linux-image-c1
      - u-boot
      - u-boot-tools
      - bootini

      # Special X11 packages for the ODROID
      - mali-x11/unstable
      - xserver-xorg-video-mali/unstable

      # Special KWin packages for the ODROID
      - kwin-x11=4:5.4.80+git20151029.1240+9-0
      - kwin-common=4:5.4.80+git20151029.1240+9-0
      - kwin-data=4:5.4.80+git20151029.1240+9-0

      # Special Calamares package for ODROID
      - calamares=0+git20151103.1711+9-0
      - calamares-branding=1+git20150825.2330+9

      # Special extra packages for ODROID
      - krfb # Has a few random patches
      - netrunner-default-settings=1.3.1+git20151024.1422+9
      - zram-config
      - mintupdate
  :bootloader:
    :config:
      :src: boot.ini.erb
      :dst: boot/boot.ini
    :uboot:
      :bl1:
        :file: usr/share/c1_uboot/bl1.bin.hardkernel
        :dd_opts: "bs=1 count=442"
      :SPL:
        :file: usr/share/c1_uboot/bl1.bin.hardkernel
        :dd_opts: "bs=512 skip=1 seek=1"
      :img:
        :file: usr/share/c1_uboot/u-boot.bin
        :dd_opts: "bs=512 seek=64"
